# docker compose run --no-deps rails rails new . --force --database=postgresql --platform linux/amd64

version: '3.7'
services:
  db:
    image: 'postgres:latest'
    platform: linux/x86_64
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails:
    build: ./ 
    platform: linux/x86_64
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container

volumes:
  postgres: # named volume